### ISSUE TITLE
Dev Meeting Agenda 2020-12-16

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/long-term-eng#10]
[Link to last meeting](https://github.com/CouncilDataProject/long-term-eng/issues/9)

---

* [x] Catch-Up
* [x] Done
  * [x] Migration of `EventIngestionModel` and other "ingestion" models https://github.com/CouncilDataProject/cdp-backend/issues/10 and  https://github.com/CouncilDataProject/cdp-backend/pull/26
  * [x] Updated storybook docs https://github.com/CouncilDataProject/cdp-frontend/pull/20
  * [x] Renamed from `cdp-instance` to `cdp-frontend` and released `0.2.0` https://github.com/CouncilDataProject/cdp-frontend/pull/22
* [x] Doing
  * [x] Creation of `EventProcessingPipeline` https://github.com/CouncilDataProject/cdp-backend/issues/16
  * [x] Update existing components w/ Mozilla Styling https://github.com/CouncilDataProject/cdp-frontend/issues/11
  * [x] Generate example data function https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/pull/9
  * [x] Test out and finalize logo https://github.com/CouncilDataProject/councildataproject.github.io/issues/8
* [x] To do
  * [x] Resolve "public read" issue https://github.com/CouncilDataProject/cdp-backend/issues/14
  * [x] Deploy `example` repo
  * [x] Update GitHub Actions and packages with new deployment workflow https://github.com/AllenCellModeling/cookiecutter-pypackage/pull/61
  * [x] Use example data with planned `EventPipeline` CI https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/3
  * [x] Exportable app https://github.com/CouncilDataProject/cdp-frontend/issues/13
* [x] Planning
  * [x] General CouncilDataProject website and landing https://github.com/CouncilDataProject/councildataproject.github.io/issues/4
  * [x] `EventIndexPipeline` and Index models https://github.com/CouncilDataProject/cdp-backend/issues/23
* [x] Admin
