### ISSUE TITLE
Dev Meeting Agenda 2020/11/18

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/long-term-eng#8]
* [x] Intro Hawk / Catch-Up
* [x] `cdp-backend`
  * [x] Database models
  * [x] Infrastructure module
  * [x] Pre-release version
  * [x] Migration of `EventData` and other "ingestion" objects (@isaacna) [#10](https://github.com/CouncilDataProject/cdp-backend/issues/10)
  * [x] Creation of `EventPipeline` (unassigned ) [#16](https://github.com/CouncilDataProject/cdp-backend/issues/16)
  * [x] Resolve "public read" issue (needed for `example` deployment) (unassigned) [#14](https://github.com/CouncilDataProject/cdp-backend/issues/14)
* [x] `cdp-frontend`
  * [x] Update your upstreams -- `main` is now primary branch
  * [x] Mozilla styling
  * [x] Exportable app (unassigned) [#13](https://github.com/CouncilDataProject/cdp-instance/issues/13)
* [x] `cookiecutter-cdp-deployment`
  * [x] Generate example data function (@tohuynh) [#2](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/2)
  * [x] Use example data with planned `EventPipeline` CI (unassigned) [#3](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/3)
  * [x] Deploy `example` repo (@JacksonMaxfield)
  * [x] Managing deployment upgrades -- `Makefile` for post-cookiecutter
* [x] `councildataproject.github.io`
  * [x] Redesign in-progress (@JacksonMaxfield)
* [x] Admin
  * [x] Logo

**Comment by JacksonMaxfield** [comment]
* @isaacna self-assigned [#16](https://github.com/CouncilDataProject/cdp-backend/issues/16) (Thanks!)

* Hawk to take the `cdp-instance` Mozilla styling issue

* @tohuynh had updates on the `generate-synthetic-data` function to be added to our example deployment when ready.

* Logo is still in progress :tada: 

---

All of us are a bit busy with stuff but progress still occurring!
