### ISSUE TITLE
Dev Meeting Agenda 2020-12-02

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/long-term-eng#9]
* [x] Intro Nick / Catch-Up
* [x] `cdp-backend`
  * [x] Adopted `mypy` for type checking [#21](https://github.com/CouncilDataProject/cdp-backend/pull/21)
  * [x] Fixed UML Diagram [#22](https://github.com/CouncilDataProject/cdp-backend/pull/22)
  * [x] Migration of `EventData` and other "ingestion" objects (@isaacna) [Issue #10](https://github.com/CouncilDataProject/cdp-backend/issues/10) [PR #20](https://github.com/CouncilDataProject/cdp-backend/pull/20)
  * [x] Creation of `EventPipeline` (@isaacna) [#16](https://github.com/CouncilDataProject/cdp-backend/issues/16)
  * [x] Resolve "public read" issue (unassigned) [#14](https://github.com/CouncilDataProject/cdp-backend/issues/14)
* [x] `cdp-frontend`
  * [x] Update existing components w/ Mozilla Styling (@hawkticehurst) [#11](https://github.com/CouncilDataProject/cdp-instance/issues/11)
  * [x] Exportable app (unassigned) [#13](https://github.com/CouncilDataProject/cdp-instance/issues/13)
* [x] `cookiecutter-cdp-deployment`
  * [x] Generate example data function (@tohuynh) [#2](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/2)
  * [x] Use example data with planned `EventPipeline` CI (unassigned) [#3](https://github.com/CouncilDataProject/cookiecutter-cdp-deployment/issues/3)
  * [x] Deploy `example` repo (@JacksonMaxfield)
* [x] `councildataproject.github.io`
  * [x] Redesigned [#2](https://github.com/CouncilDataProject/councildataproject.github.io/pull/2)
  * [x] Add more detail and fix minor bugs (@JacksonMaxfield) [[#3](https://github.com/CouncilDataProject/councildataproject.github.io/issues/3), [#4](https://github.com/CouncilDataProject/councildataproject.github.io/issues/4), [#5](https://github.com/CouncilDataProject/councildataproject.github.io/issues/5)]
* [x] Admin
  * [x] Logo
  * [x] Across the Board Documentation Updates
